### PR TITLE
chore(package.json): update packages

### PR DESCRIPTION
**Pull request by FeliciousX**

### CODE REVIEW

**Comment by Widdershin** [comment]
@FeliciousX, any idea why the test might be failing on CI? Could you look into that?

Thanks for updating these, I should really set up greenkeeper.

**Comment by FeliciousX** [comment]
I identified the error to be from [v6.0.0](https://github.com/staltz/xstream/blob/master/CHANGELOG.md#600-2016-08-20)

@Widdershin 

but I'm not sure how to fix it yet. Will check it out in more detail

**Comment by FeliciousX** [comment]
hmm I don't know how to fix it. It seems like when the stream ends, suddenly the whole thing just breaks before it can finish the test.

Just like what what `v6.0.0` of xstream is saying, the behavior have changed.

I tried and failed :( @Widdershin maybe some fresh eyes would help

**Comment by Widdershin** [comment]
I had a little look but couldn't see what the issue is. @Hypnosphi is more familiar with the gather code than I am. Do you have any thoughts @Hypnosphi?

**Comment by Hypnosphi** [comment]
OK, I'll try to debug it

**Comment by Hypnosphi** [comment]
Is it just me, or this thing doesn't reproduce locally?

**Comment by Hypnosphi** [comment]
looks like the problem was that `addReducer$` completed synchronously, before than `removeReducer$` even started

**Comment by FeliciousX** [comment]
thank you @Hypnosphi  <3

**Pull request merged**
