### PR TITLE
Diversity

### LINKED ISSUE #20: support for stream lib adapters
It would be nice if we could easily use Collection with other stream libs besides xstream, perhaps by supplying our stream adapter of choice to `Collection()` - as suggested by @Hypnosphi on gitter. Currently there seems to be a hard requirement for xstream sources only, so things break if our app's components use RxJS.

### PR DESCRIPTION
**Pull request by geovanisouza92**
Closes #20

### CODE REVIEW

**Comment by Widdershin** [comment]
Hi @geovanisouza92,

This looks really fantastic, thank you for doing this work.

It's weird that the node 4 build is failing. I've disabled it for the moment. Can you please pull in master to get the new travis config?

**Comment by TylorS** [comment]
@Widdershin FWIW its failing on node 4 because NPM v2 doesn't know how to resolve a version of rxjs 5 beta that satifies `*`, which is not intuitive.

**Comment by Widdershin** [comment]
Cheers for that @TylorS, I figured it was some NPM weirdness. Anything we can do about it?

**Comment by TylorS** [comment]
Sadly no, we've disabled node 4, or ignore that it fails on all the projects I work with (if its an issue). NPM v2 will still work when you install a version of rxjs 5, and better yet, node 4 can also update to NPM v3 which is what I recommend. 

Perhaps some docs on that is all we need?

**Comment by TylorS** [comment]
Actually, it's probably possible to create a script to run before the tests to upgrade to NPM 3

**Comment by geovanisouza92** [comment]
After submitting the PR I was thinking to replace Rx 5 by Rx 4, to avoid this problem with the CI. But, you know, was late and I went to sleep :joy:

**Comment by Hypnosphi** [comment]
Great!

**Pull request merged**
