### PR TITLE
chore(package): bump xstream and isolate version

### PR DESCRIPTION
**Pull request by FeliciousX**
Updating cycle/collection to use latest version of xstream

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Can we maybe remove some `.remember()` calls because of this: https://github.com/staltz/xstream/commit/116e9f2e33cf8f7ad45da31e99e1e99aee0bad9a

**Comment by FeliciousX** [comment]
u mean for these lines?
https://github.com/cyclejs/collection/blob/master/src/collection.js#L108-L110

@Hypnosphi

**Comment by Hypnosphi** [comment]
Yes, and in the todo example 
https://github.com/cyclejs/collection/blob/master/examples/todolist/app.js#L25
https://github.com/cyclejs/collection/blob/master/examples/todolist/app.js#L79

**Comment by FeliciousX** [comment]
btw the `remember` on collection.js cannot be removed. it will cause some bugs. so I kept it @Hypnosphi

**Comment by Widdershin** [comment]
Y'all rule!

**Comment by FeliciousX** [comment]
I'll leave it to you for publishing the package when u think it's ready @Widdershin  😄

**Comment by Widdershin** [comment]
Published as v0.1.2

**Pull request merged**
